# This file was generated by GoReleaser. DO NOT EDIT.
cask "bb" do
  version "2.1.0"

  on_macos do
    sha256 "51d8c53a4c15071c0c24513765f0ed00be86acd6a5e3b92d68f0d5bffd96be43"
    url "https://github.com/chandrasekar-r/bitbucket-cli/releases/download/v#{version}/bb_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "a4883eddb83ce5c9eb7b54b83a5dd1079a11f1ed4a25559016294ed8d51d1779"
      url "https://github.com/chandrasekar-r/bitbucket-cli/releases/download/v#{version}/bb_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bf4e36d07d5e9702ee393a982819d017eb30049c6b7e4f0d237762c48a004548"
      url "https://github.com/chandrasekar-r/bitbucket-cli/releases/download/v#{version}/bb_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bb"
  desc "Bitbucket Cloud CLI"
  homepage "https://github.com/chandrasekar-r/bitbucket-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bb"

  # No zap stanza required

end
