# This file was generated by GoReleaser. DO NOT EDIT.
cask "bb" do
  version "0.2.0"

  on_macos do
    sha256 "b63e61284bbc8ea334a95a614c5b2f9a8c712aeb1083142bfabb353aaa991ef7"
    url "https://github.com/chandrasekar-r/bitbucket-cli/releases/download/v#{version}/bb_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "ccb85c4d12ccc7bc8f7071c151f5b17668c362fea463f09d5980270822668eb5"
      url "https://github.com/chandrasekar-r/bitbucket-cli/releases/download/v#{version}/bb_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a1ccd5eccaf82fc8438ca7a358697810d5a03df9799e64cf359607cf6c4a1b34"
      url "https://github.com/chandrasekar-r/bitbucket-cli/releases/download/v#{version}/bb_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bb"
  desc "Bitbucket Cloud CLI"
  homepage "https://github.com/chandrasekar-r/bitbucket-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bb"

  # No zap stanza required

end
