# This file was generated by GoReleaser. DO NOT EDIT.
cask "bb" do
  version "0.3.0"

  on_macos do
    url "https://github.com/chandrasekar-r/bitbucket-cli/releases/download/v#{version}/bb_#{version}_darwin_all.tar.gz"
    sha256 "9c826a55f6f401a0d16720370d4f1164aa92c3598f437f35234cb72e8006aa5a"
  end

  on_linux do
    on_intel do
      url "https://github.com/chandrasekar-r/bitbucket-cli/releases/download/v#{version}/bb_#{version}_linux_amd64.tar.gz"
      sha256 "22c06bf83fc668a7424691b418eb568e66d529db43d80648db4c4b8b8640fe62"
    end
    on_arm do
      url "https://github.com/chandrasekar-r/bitbucket-cli/releases/download/v#{version}/bb_#{version}_linux_arm64.tar.gz"
      sha256 "7a2e2f762694d72b9cdfe315a4d7d0633b297e4026c0064df46ec5edfc0cf01c"
    end
  end

  name "bb"
  desc "Bitbucket Cloud CLI"
  homepage "https://github.com/chandrasekar-r/bitbucket-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bb"

  # No zap stanza required

end
